{
  "PAGE_AUTHOR": "PLACEHOLDER_PAGE_AUTHOR",
  "FULL_NAME": "PLACEHOLDER_FULL_NAME",
  "GITHUB_USER": "PLACEHOLDER_GITHUB_USER",
  "NODE_VERSION": "PLACEHOLDER_NODE",
  "NPM_USER": "PLACEHOLDER_NPM_USER",
  "REPO_NAME": "PLACEHOLDER_REPO_NAME",
  "endJsonFile": "special key for safe JSON encoding"
}
